theme: jekyll-theme-architect
title: BizKit
description: Business Support Services
# Your name to show in the footer
author: Luke~S

# --- List of links in the navigation bar --- #
navbar-links:
  About Me: "aboutme"
  Resources:
#    - Beautiful Jekyll: "https://beautifuljekyll.com"
#    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://www.stockburger.xyz"

# --- Logo --- #
# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/logo1.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true
